### ISSUE TITLE
Support managed cached values

### ISSUE THREAD

**Issue by vigoo** [zio/zio-cache#50]
It would be nice to be able to cache `ZManaged` values that gets released when they get out from the cache.

**Comment by ithinkicancode** [comment]
Hi @vigoo, can you elaborate or can you give an example? Currently, a cache value is stored as `exit: Exit[Error, Value]` in the `MapValue.Complete` case class. Do you mean it should be replaced as `exit: ZManaged[Any, Error, Value]`?

**Comment by adamgfraser** [comment]
@ithinkicancode The `lookup` function would return a `ZManaged` instead of a `ZIO` and then when the lookup function is run we would evaluate the `acquire` action of the `ZManaged` and store the release action in the cache, running it when the cache entry was evicted. The entire cache would likely be created in the context of a managed effect to ensure that all acquired resources were released when that scope was closed.

**Comment by strokyl** [comment]
I start working on that issue but would appreciate some advice if possible (see #7 )

**Comment by jdegoes** [comment]
The interface of the cache itself must change, since the resource management mechanism must be aware of when a resource is done being used. This implies: not only is the `lookup` function resourceful, but also the `get` function on the cache is resourceful.

@adamgfraser It will be interesting to see how this shakes out in a 2.0 world.

**Comment by strokyl** [comment]
I think I got something working on #71 and I would appreciate some feedback on the question I added as comments in my code before going forward with this PR.
